/**
 * Exports categories + products from the local Postgres dev database into
 * a D1-compatible seed.sql (SQLite dialect: booleans as 0/1, features as
 * JSON text, timestamps as unix-ms).
 *
 * Run:  DATABASE_URL=... pnpm --filter @workspace/scripts run export-to-d1
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { db, categoriesTable, productsTable, pool } from "@workspace/db";
import { asc } from "drizzle-orm";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../../d1/seed.sql");

function sqlStr(v: string | null | undefined): string {
  if (v === null || v === undefined) return "NULL";
  return `'${v.replace(/'/g, "''")}'`;
}

function sqlNum(v: string | number | null | undefined): string {
  if (v === null || v === undefined) return "NULL";
  const n = typeof v === "string" ? Number(v) : v;
  return Number.isFinite(n) ? String(n) : "NULL";
}

async function main() {
  const cats = await db.select().from(categoriesTable).orderBy(asc(categoriesTable.id));
  const products = await db.select().from(productsTable).orderBy(asc(productsTable.id));

  const lines: string[] = [];
  lines.push("-- Generated by scripts/src/export-to-d1.ts — do not hand-edit.");
  lines.push("DELETE FROM order_items;");
  lines.push("DELETE FROM reviews;");
  lines.push("DELETE FROM orders;");
  lines.push("DELETE FROM products;");
  lines.push("DELETE FROM categories;");

  for (const c of cats) {
    lines.push(
      `INSERT INTO categories (id, name, slug, description, icon, created_at) VALUES ` +
        `(${c.id}, ${sqlStr(c.name)}, ${sqlStr(c.slug)}, ${sqlStr(c.description)}, ${sqlStr(c.icon)}, ${c.createdAt.getTime()});`,
    );
  }

  for (const p of products) {
    const features = p.features ? JSON.stringify(p.features) : null;
    lines.push(
      `INSERT INTO products (id, name, description, price_bdt, original_price_bdt, category_id, image_url, features, duration_days, is_active, is_featured, stock_count, order_count, created_at) VALUES ` +
        `(${p.id}, ${sqlStr(p.name)}, ${sqlStr(p.description)}, ${sqlNum(p.priceBdt)}, ${sqlNum(p.originalPriceBdt)}, ${p.categoryId}, ${sqlStr(p.imageUrl)}, ${sqlStr(features)}, ${p.durationDays ?? 30}, ${p.isActive ? 1 : 0}, ${p.isFeatured ? 1 : 0}, ${p.stockCount ?? 100}, ${p.orderCount}, ${p.createdAt.getTime()});`,
    );
  }

  writeFileSync(OUT, lines.join("\n") + "\n");
  console.log(`✓ Wrote ${cats.length} categories + ${products.length} products to ${OUT}`);
  await pool.end();
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
