-- AIPT Commercial Truth v2 — approved 2026-09-17
--
-- REFERENCE / RECOVERY SQL ONLY.
-- Runtime commercial truth is enforced by:
--   ops/aipt-pricing-v2.json
--   functions/lib/commercial-policy.ts
--   functions/_middleware.ts
-- Production normalization is performed through the isolated Pages-bound
-- function in scripts/ops/aipt-commercial-v2-pages-function.ts so that the
-- same policy module governs D1 normalization and checkout.
--
-- This file remains idempotent for emergency/manual recovery and MUST be kept
-- in parity with the runtime policy. Legacy rows are retained for audit/history.

-- Default deny every row first. Credential-shared rows are prohibited and
-- non-indexed; all other unmapped rows are held for current verification.
UPDATE products
SET
  is_active = 0,
  is_featured = 0,
  stock_count = 0,
  commercial_state = CASE
    WHEN lower(name) LIKE '%shared%' THEN 'PROHIBITED'
    ELSE 'HOLD'
  END,
  seo_index = CASE
    WHEN lower(name) LIKE '%shared%' THEN 0
    ELSE seo_index
  END,
  updated_at = CAST(unixepoch('subsec') * 1000 AS INTEGER);

-- Active rows use evidence-safe generic copy; provider feature details stay out
-- of D1 commercial copy unless separately verified.

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=3390, original_price_bdt=NULL, is_active=1, is_featured=1, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'ChatGPT Plus%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=1299, original_price_bdt=NULL, is_active=1, is_featured=1, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'ChatGPT Go%Personal%';

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=3390, original_price_bdt=NULL, is_active=1, is_featured=1, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Claude Pro%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=16790, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Claude Max 5x%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=33590, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Claude Max 20x%Personal%';
UPDATE products SET name='Claude Team Standard — Workspace Seat', description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=4290, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='AUTHORIZED_SEAT', plan_type='monthly', delivery_type='provider_workspace_seat', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Claude Team%Seat%';

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=3390, original_price_bdt=NULL, is_active=1, is_featured=1, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Google AI Pro%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=5090, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'SuperGrok%Personal%' AND name NOT LIKE '%Lite%';

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=3390, original_price_bdt=NULL, is_active=1, is_featured=1, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Perplexity Pro%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=33590, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Perplexity Max%Personal%';

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=5090, original_price_bdt=NULL, is_active=1, is_featured=1, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Midjourney Standard%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=10090, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Midjourney Pro%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=20190, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Midjourney Mega%Personal%';

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=3390, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Ideogram Plus%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=10090, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Ideogram Pro%Personal%';

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=2690, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Runway Standard%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=5890, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Runway Pro%Personal%';

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=1390, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'ElevenLabs Starter%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=3690, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'ElevenLabs Creator%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=16690, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'ElevenLabs Pro%Personal%';

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=1990, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Suno AI Pro%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=5090, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Suno AI Premier%Personal%';

UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=1990, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'GitHub Copilot Pro%Personal%' AND name NOT LIKE '%Pro+%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=6590, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'GitHub Copilot Pro+%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=3390, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Cursor Pro%Personal%' AND name NOT LIKE '%Pro+%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=10090, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Cursor Pro+%Personal%';
UPDATE products SET description='AIPT approved direct-sale plan with current BDT pricing and provider-compatible activation. Provider features, limits, taxes and availability follow the provider''s current terms.', price_bdt=3390, original_price_bdt=NULL, is_active=1, is_featured=0, stock_count=100, commercial_state='CUSTOMER_OWNED', plan_type='monthly', delivery_type='customer_account_activation', seo_index=1, updated_at=CAST(unixepoch('subsec')*1000 AS INTEGER) WHERE name LIKE 'Replit Core%Personal%';
